### PR TITLE
Add MIT license

### PR DESCRIPTION
**Pull request by tomas-polach**
I've been noticed that this open-source project is missing the MIT license. Suggesting to add it here.

### CODE REVIEW

**Comment by tomas-polach** [comment]
@frederic-schwarz would you mind to review & merge this PR? (missing MIT license)

**Comment by frederic-schwarz** [comment]
@tomas-polach the PR assigns the copyright to Murat Corlu, is this intended?

**Comment by jonhainstock** [comment]
Thanks for adding this PR, @tomas-polach. I wonder if Murat was copied and pasted from another license?

**Comment by tomas-polach** [comment]
Yes, you are right, that was copy-pasted from another project 😅 Fixed now

**Review by frederic-schwarz — APPROVED** [review]

**Comment by jonhainstock** [comment]
Thanks, guys!

**Comment by tomas-polach** [comment]
Thanks @frederic-schwarz 🙌

**Pull request merged**
